### ISSUE TITLE
Request for editorials for every problem you solve on the stream.

### ISSUE THREAD

**Issue by strikersps** [Errichto/youtube#2]
Hi Errichto, hope you are doing well. First of all I really appreciate the work you are doing on youtube.

I just have one request that, it would be nice if you can add a small editorial about the the code & algorithms which you have used in order to solve the problem.  It would be really helpful.  

In one way I am asking you to give an editorial which should be beginner friendly, I know the problems which you are solving from different platforms and online judges will have an editorial, and we can all refer to them, but those editorial doesn't tell why this algorithm is used to solve the problem as compare to other algorithms, or if there is an advanced data-structure being used to solve the problem, could it be possible if you can explain the benefits of using those advanced data-structures and algorithm in such type of problems.  

In summary I am asking you to explain your approach of solving the problem or if the problem belong to a particular class of the problem (i.e Divide and Conquer, Greedy, Dynamic Programming, Game Theory) then how would it should be solved, what should be the thought process.  

You are explaining it in live-stream but it would be better if you can write a small editorial of every problem you solve explaining your thought-process, so that I and other viewers can refer to after the stream is finished.  It would really help us.  

What I am talking about is:
In the stream [Google Kickstart, Leetcode, Codeforces](https://www.youtube.com/watch?v=w3W-w0EXEtc) you solved many problems and it was really helpful for me.  
There was problem [Balanced Rating Changes](https://codeforces.com/contest/1237/problem/A) from the [Codeforces Global Round 5 by tourist](https://codeforces.com/contest/1237) and while solving the problem you said there is difference between using `x >> 1` and `x / 2` instruction.  
Like this there are many other small and important things which you have said related to competitive programming when solving problems during the whole stream which are not in FAQ.     
If you can add all those points as a summary in a document and upload in this repository like a summary of a stream.  

Thanks

**Comment by Errichto** [comment]
Feel free to write down what I do during streams. It feels very unnecessary/redundant though and I don't see a value in writing this down on the top of saying it. I don't have time for that, sorry.

**Comment by strikersps** [comment]
@Errichto Well thanks for replying, currently maybe there is no value of writing down the things on top of saying it but later it will have.  
I was just asking for a small editorial, no problem I will note down from the videos.  
Thanks
