### ISSUE TITLE
Suggestion about learning resources on Segment Tree

### ISSUE THREAD

**Issue by svaderia** [Errichto/youtube#7]
[Algorithm Gym :: Everything About Segment Trees](https://codeforces.com/blog/entry/15890)  
Source : [All the good tutorials found for Competitive Programming](https://codeforces.com/blog/entry/57282)

**Comment by Errichto** [comment]
How is this about my github repository? Yes, there are a lot of good resources out there.

**Comment by svaderia** [comment]
I thought you were planning to extend your [Learning Resources wiki](https://github.com/Errichto/youtube/wiki/Learning-resources) with different useful resources. So this was just a suggestion to consider. It's not related to your YT or GitHub directly.
